src/styles/app.styl
=> Modal color hotfix

src/store/modules/workshops.js
add marko workshop replay youtube url
=> Marko workshop replay url

package-lock.json, package.json, public/index.html, src/App.vue, src/views/GameOfZones.vue, src/views/Ibc.vue, src/views/NewslettersSignupCosmos.vue, src/views/NewslettersSignupIbc.vue, src/views/NewslettersSignupTools.vue
closes https://github.com/allinbits/design/issues/296
=> ML Migration

src/styles/app.styl
remove --white-100 after cosmos-ui bump
=> Remove --white-100

src/assets/images/home/section-planet.svg, src/components/common/AppLaunchBanner.vue, src/components/common/TmSection.vue, src/router.js, src/views/Index.vue
closes https://github.com/allinbits/design/issues/292
=> Stargate Updates on cosmos.network

package-lock.json, package.json, src/store/modules/workshops.js, src/views/EventCodewithus.vue, src/views/Workshop.vue
- use PDT as the base time
- automatically convert to client's local timezone using moment-timezone
- hide date in the pastWorkshops section when there is no replay url
=> Timezone for the workshop time

src/swagger.json
Update Swagger URLs to match files in the Cosmos SDK repo.
=> Update Swagger URLs

public/top-banner/index.json
`Prepare for Stargate testnet, coming soon → ` to  `Stargate is live! Join the testnet → `
=> Docs top banner

src/components/cards/TmCardHz.vue, src/components/common/AppTopBanner.vue, src/components/common/TmSection.vue, src/views/Community.vue
- update top banner bg gradient
- update tm-section 2n-1 bg to transparent
- featured events must be future events
=> minor tweaks

src/views/Tools.vue
closes https://github.com/cosmos/cosmos.network/issues/117
=> Add cosmosswift to /tools

src/views/Contributors.vue
Added links to contributors page for guidelines to meetups and media/content contributions.
=> Contribution guidelines links

src/views/Community.vue
- Telegram: Developer Chat → Community Chat
=> Community Page - Telegram

src/assets/images/sdk/section-ecosystem-logos-1.svg, src/assets/images/sdk/section-ecosystem-logos-2.svg
Solved SVG clipping issue due to the mix blending mode for the app icons on the ecosystem section.
=> SVG Refinement on SDK page

src/store/modules/resources.js, src/views/Ibc.vue
closes https://github.com/cosmos/cosmos.network/issues/136
=> IBC updates sign up: Zoho → MailerLite

public/top-banner/index.json, src/components/common/AppTopBanner.vue
Ref: https://github.com/allinbits/design/issues/359
=> Stargate top banner

package-lock.json, package.json, src/router.js, src/views/NewslettersSignupCosmos.vue, src/views/NewslettersSignupIbc.vue, src/views/NewslettersSignupTools.vue, src/views/NewslettersSignupValidators.vue
closes https://github.com/allinbits/design/issues/368
https://deploy-preview-145--cosmos-network.netlify.app/newsletters/signup/validators
=> Validators Newsletter

src/store/modules/blog.js, src/views/Ecosystem.vue, src/views/Wallets.vue
Ref: https://github.com/allinbits/design/issues/374
=> hot fix for blogrss

public/top-banner/index.json, src/components/common/AppTopBanner.vue
closes https://github.com/allinbits/design/issues/390
=> Update top banner copy

content/md/resources-faq.md, src/views/Community.vue, src/views/Developers.vue, src/views/Launch.vue
Ref: https://github.com/cosmos/cosmos.network/issues/163
=> Replace hub.cosmos.network/master → /main

src/router.js
closes https://github.com/allinbits/design/issues/394
=> add more /socials redirects

src/store/modules/marketcap.js
https://backend.tendermint.com/marketcap
Ref: https://github.com/allinbits/design/issues/375
=> Replace backend url

src/views/Ecosystem.vue
closes https://github.com/allinbits/design/issues/407
=> Add dot color for live label

package-lock.json, package.json
Pulled the latest glossary list from https://github.com/tendermint/cosmos-ui/pull/218
Before
After
=> Bump glossary list
